# Base image olarak resmi Node.js imajını kullanıyoruz
FROM node:18-alpine

# Uygulama dosyalarının çalışacağı dizini belirliyoruz
WORKDIR /src

# package.json ve package-lock.json dosyalarını kopyalıyoruz
COPY package*.json ./

# Proje bağımlılıklarını yüklüyoruz
RUN npm install

# Uygulama dosyalarını kopyalıyoruz
COPY . .

# Typescript dosyalarını JavaScript'e dönüştürüyoruz
RUN npm run build

# Nodemon, PM2, TSX, ve Drizzle-Kit gibi global bağımlılıkları yüklüyoruz
RUN npm install -g pm2 tsx drizzle-kit

# Uygulamanın çalışacağı portu belirtiyoruz
EXPOSE 3000

# Uygulamanın başlatılacağı komutu belirtiyoruz
CMD ["pm2-runtime", "start", "src/index.ts", "--name", "taskpeerapi"]
