name: Task Peer API

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SECRET_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd ${{ secrets.RELEASE_PATH }}
            cd ${{ secrets.RELEASE_PATH }}/src/db
            docker-compose up -d
            cd ..
            git pull origin release
            rm -r ${{ secrets.RELEASE_PATH }}/src/db/migrations/*
            npm install
            npm run db:genarete
            npm run db:migrate
            npm run deploy
